---
title: "Linear Transformation"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(EnsCat)
library(class)
library(caret)
library(gmodels)
library(mltest)
```

```{r}
poker_train <- read.csv("/Users/laurenflemmer/Desktop/poker_proj/data/poker-hand-training-true.data")
poker_test <- read.csv("/Users/laurenflemmer/Desktop/poker_proj/data/poker-hand-testing.data")

# make test set smaller for efficiency
poker_test <- sample_n(poker_test, 200000)

# histogram of hands
hist(poker_train[,11])

poker_cards_train = poker_train %>% select(1:10)
poker_cards_test = poker_test %>% select(1:10)
poker_hand_train = poker_train %>% select(11)
poker_hand_test = poker_test %>% select(11)

train_suits <- poker_cards_train %>% select(1, 3, 5, 7, 9)
train_values <- poker_cards_train %>% select(2, 4, 6, 8, 10)

# Changing variable names to be readable
var_names <- c("S1", "C1", "S2", "C2", "S3", "C3", "S4", "C4", "S5", "C5")
colnames(poker_cards_test) <- var_names
colnames(poker_cards_train) <- var_names

# looking at the distribution of suits and cards as well as means
boxplot(train_suits)
colMeans(train_suits)

boxplot(train_values)
colMeans(train_values)

# checking to see if the proportion of hands is roughly even between test and train data
prop.table(table(poker_test[,11]))
prop.table(table(poker_train[,11]))


```

```{r}

# Data transformation: new data frame with 18 columns. 
# 1 column for each rank 1-13
# 4 columns for frequency of suits 1-4
# 1 column for outcome (unchanged)

rank <- c(seq(1, 13))
suit <- c("clubs", "diamonds", "hearts","spades")

# A function that will take data and transform into a new space

lineartransform <- function(df){
  dfnew <- data.frame(matrix(ncol = 18, nrow = nrow(df)))
  dfnew[is.na(dfnew)] <- 0
  colnames(dfnew) <- c(rank, suit, "hand")
  
  dfnew$hand <- df[,11]

  for (i in 1:nrow(df)){
    for (j in 1:5){
      card <- 2*j
      suit <- 2*j-1
      index <- df[i, card]
      newsuit <- df[i, suit] + 13
      dfnew[i, index] <- dfnew[i, index] + 1
      dfnew[i, newsuit] <- dfnew[i, newsuit] + 1
    }
  }
  return(dfnew)
}

traindata_transformed <- lineartransform(poker_train)
testdata_transformed <- lineartransform(poker_test)

```

```{r}
write.csv(traindata_transformed, "/Users/laurenflemmer/Desktop/poker_proj/data/poker-hand-training-transformed.csv", row.names=FALSE)

write.csv(testdata_transformed, "/Users/laurenflemmer/Desktop/poker_proj/data/poker-hand-test-transformed.csv", row.names=FALSE)
```
